---
- name: 0.系统初始化
  gather_facts: false
  hosts: all
  roles:
    - init
  tags: init

- name: 1.部署k3s集群
  gather_facts: false
  hosts: k3s
  roles:
    - k3s
  tags: k3s

- name: 2.安装helm
  gather_facts: false
  hosts: localhost
  roles:
    - helm
  tags: helm

- name: 3.自签证书
  gather_facts: false
  hosts: localhost
  roles:
    - tls
  tags: tls

- name: 4.部署rancher集群
  gather_facts: false
  hosts: localhost
  roles:
    - rancher
  tags: rancher
